id: I3EDCAC4A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T02:42:26+00:00'
last_modified: '2022-06-07T18:57:02.658639+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14138
  title: བོད་ཀྱི་བརྡ་སྤྲོད་ནག་ཊིཀཿ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    DC6D:
      image_group_id: I1KG14332
      title: ''
      total_pages: 584
      order: 1
      base_file: DC6D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
